# Generated by Django 4.1.7 on 2023-03-12 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0065_rename_contart_personel_contrat'),
        ('Resident', '0007_contact_sent_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='payment',
            new_name='Creditpayment',
        ),
    ]
