# Generated by Django 4.1.7 on 2023-03-12 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0008_rename_payment_creditpayment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditpayment',
            options={'verbose_name': 'Library Book'},
        ),
    ]
