# Generated by Django 4.1.7 on 2023-03-12 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0009_alter_creditpayment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditpayment',
            options={'verbose_name': 'Credit Payment'},
        ),
    ]
