# Generated by Django 4.1.7 on 2023-03-13 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0070_fournisseurs_date'),
        ('Resident', '0011_travauxpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='travauxpayment',
            name='traveaux',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.fournisseurs'),
        ),
    ]
