# Generated by Django 4.1.7 on 2023-03-14 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0013_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='timestamp',
        ),
    ]
