# Generated by Django 4.1.7 on 2023-03-14 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0014_remove_notification_is_read_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
    ]
