# Generated by Django 4.1.7 on 2023-03-16 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0018_notification_sent_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
