# Generated by Django 4.1.7 on 2023-04-27 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0076_delete_email'),
        ('Resident', '0021_alter_creditpayment_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditpayment',
            name='Appartment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.appartment'),
        ),
        migrations.AlterField(
            model_name='creditpayment',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.profile'),
        ),
    ]
