# Generated by Django 4.1.2 on 2023-05-09 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0082_chatmessage_created_at'),
        ('Resident', '0022_creditpayment_appartment_alter_creditpayment_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travauxpayment',
            name='user',
        ),
        migrations.AddField(
            model_name='travauxpayment',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.profile'),
        ),
    ]
