# Generated by Django 4.1.2 on 2023-05-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0023_remove_travauxpayment_user_travauxpayment_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='recu',
            field=models.FileField(null=True, upload_to='reclamation/'),
        ),
    ]
