# Generated by Django 4.1.2 on 2023-05-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0027_alter_contact_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='image',
        ),
        migrations.AddField(
            model_name='contact',
            name='recu',
            field=models.FileField(null=True, upload_to='recu/'),
        ),
    ]
