# Generated by Django 4.1.2 on 2023-05-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0029_rename_recu_contact_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=models.FileField(null=True, upload_to='img/reclamation'),
        ),
    ]
