# Generated by Django 4.1.2 on 2023-05-13 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0031_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
    ]
