# Generated by Django 4.1.7 on 2023-02-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_profile_appartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='CIN',
            field=models.BigIntegerField(default=1235),
        ),
    ]
