# Generated by Django 4.1.7 on 2023-02-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0028_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/img/23/avatar.png', null=True, upload_to='img/%y'),
        ),
    ]
