# Generated by Django 4.1.7 on 2023-03-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0031_sms'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='phone',
            field=models.BigIntegerField(default=4),
        ),
    ]
