# Generated by Django 4.1.7 on 2023-03-02 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0032_sms_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sms',
        ),
    ]
