# Generated by Django 4.1.7 on 2023-03-02 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0034_smsmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SMSModel',
        ),
    ]
