# Generated by Django 4.1.7 on 2023-03-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0037_delete_sms'),
    ]

    operations = [
        migrations.CreateModel(
            name='personels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contart', models.FileField(max_length=254, null=True, upload_to='contrat/%y')),
                ('congée', models.IntegerField()),
            ],
        ),
    ]
