# Generated by Django 4.1.7 on 2023-03-05 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0038_personels'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='personels',
            new_name='personel',
        ),
    ]
