# Generated by Django 4.1.7 on 2023-03-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0040_profile_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='payment',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='recu',
            field=models.FileField(null=True, upload_to='recu/'),
        ),
    ]
