# Generated by Django 4.1.7 on 2023-03-08 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0043_appartment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appartment',
            old_name='resident',
            new_name='first_name',
        ),
    ]
