# Generated by Django 4.1.7 on 2023-03-08 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0044_rename_resident_appartment_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appartment',
            old_name='first_name',
            new_name='User',
        ),
    ]
