# Generated by Django 4.1.7 on 2023-03-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0045_rename_first_name_appartment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='appartment',
            field=models.CharField(choices=[], default='AS', max_length=250),
        ),
    ]
