# Generated by Django 4.1.7 on 2023-03-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0046_alter_profile_appartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='appartment',
            field=models.CharField(choices=[('Appartment Number', 'Appartement Number'), ('A1', 'a1'), ('A2', 'a2'), ('A3', 'a3'), ('A4', 'a4'), ('A5', 'a5'), ('A6', 'a6'), ('A7', 'a7')], default='AS', max_length=250),
        ),
    ]
