# Generated by Django 4.1.7 on 2023-03-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0047_alter_profile_appartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='parking_spot',
            field=models.CharField(choices=[('parking_spot', 'parking_spot'), ('P1', 'p1'), ('P2', 'p2'), ('P3', 'p3'), ('P4', 'p4'), ('P5', 'p5'), ('P6', 'p6'), ('P7', 'p7')], default='AS', max_length=250),
        ),
    ]
