# Generated by Django 4.1.7 on 2023-03-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0049_alter_profile_parking_spot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='parking_spot',
        ),
        migrations.AddField(
            model_name='profile',
            name='parking_spot',
            field=models.ManyToManyField(choices=[('Parking Spot', 'Parking Spot'), ('P1', 'p1'), ('P2', 'p2'), ('P3', 'p3'), ('P4', 'p4'), ('P5', 'p5'), ('P6', 'p6'), ('P7', 'p7')], to='authentication.parkingspot'),
        ),
    ]
