# Generated by Django 4.1.7 on 2023-03-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0050_parkingspot_remove_profile_parking_spot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='parking_spot',
        ),
        migrations.DeleteModel(
            name='ParkingSpot',
        ),
        migrations.AddField(
            model_name='profile',
            name='parking_spot',
            field=models.CharField(choices=[('Parking Spot', 'Parking Spot'), ('P1', 'p1'), ('P2', 'p2'), ('P3', 'p3'), ('P4', 'p4'), ('P5', 'p5'), ('P6', 'p6'), ('P7', 'p7')], default='AS', max_length=250),
        ),
    ]
