# Generated by Django 4.1.7 on 2023-03-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0051_remove_profile_parking_spot_delete_parkingspot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='appartment',
            field=models.CharField(choices=[], default='AS', max_length=250),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='parking_spot',
        ),
        migrations.AddField(
            model_name='profile',
            name='parking_spot',
            field=models.ManyToManyField(to='authentication.parkingspot'),
        ),
    ]
