# Generated by Django 4.1.7 on 2023-03-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0052_parkingspot_alter_profile_appartment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='appartment',
            field=models.CharField(choices=[('Appartment Number', 'Appartement Number'), ('A1', 'a1'), ('A2', 'a2'), ('A3', 'a3'), ('A4', 'a4'), ('A5', 'a5'), ('A6', 'a6'), ('A7', 'a7')], default='AS', max_length=250),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='parking_spot',
        ),
        migrations.DeleteModel(
            name='ParkingSpot',
        ),
        migrations.AddField(
            model_name='profile',
            name='parking_spot',
            field=models.CharField(choices=[('Parking Spot', 'Parking Spot'), ('P1', 'p1'), ('P2', 'p2'), ('P3', 'p3'), ('P4', 'p4'), ('P5', 'p5'), ('P6', 'p6'), ('P7', 'p7')], default='AS', max_length=250),
        ),
    ]
