# Generated by Django 4.1.7 on 2023-03-09 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0056_parkingspot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParkingSpot',
        ),
    ]
