# Generated by Django 4.1.7 on 2023-03-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0060_alter_profile_parking_spot'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='second_parking',
            field=models.CharField(choices=[('No Parking Spot', 'No Parking Spot'), ('P1', 'p1'), ('P2', 'p2'), ('P3', 'p3'), ('P4', 'p4'), ('P5', 'p5'), ('P6', 'p6'), ('P7', 'p7')], default='AS', max_length=255),
        ),
    ]
