# Generated by Django 4.1.7 on 2023-03-12 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0062_profile_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='created_at',
        ),
    ]
