# Generated by Django 4.1.7 on 2023-03-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0065_rename_contart_personel_contrat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('travaux_type', models.CharField(max_length=255)),
                ('contract', models.FileField(upload_to='Fournisseur_Contracts')),
            ],
        ),
    ]
