# Generated by Django 4.1.7 on 2023-03-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0066_fournisseurs'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseurs',
            name='frais',
            field=models.IntegerField(null=True),
        ),
    ]
