# Generated by Django 4.1.7 on 2023-03-12 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0068_alter_fournisseurs_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fournisseurs',
            options={'verbose_name': 'Fournisseur'},
        ),
    ]
