# Generated by Django 4.1.7 on 2023-03-13 13:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0069_alter_fournisseurs_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseurs',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
