# Generated by Django 4.1.7 on 2023-03-13 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0070_fournisseurs_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_messages', to='authentication.profile')),
            ],
        ),
    ]
