# Generated by Django 4.1.7 on 2023-03-13 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0071_dashboardmessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DashboardMessage',
            new_name='Notification',
        ),
    ]
