# Generated by Django 4.1.7 on 2023-03-14 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0072_rename_dashboardmessage_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
