# Generated by Django 4.1.7 on 2023-03-19 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0074_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='message',
        ),
        migrations.RemoveField(
            model_name='email',
            name='subject',
        ),
    ]
