# Generated by Django 4.1.7 on 2023-03-19 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0075_remove_email_message_remove_email_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
    ]
