# Generated by Django 4.1.2 on 2023-05-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0076_delete_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseurs',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
