# Generated by Django 4.1.2 on 2023-05-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0077_fournisseurs_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseurs',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('Pending', 'Pending')], default='AS', max_length=250),
        ),
    ]
