# Generated by Django 4.1.2 on 2023-05-03 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0080_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
